import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/toast";
const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "creme-xchange admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className}  antialiased`}><ToastProvider> {children}</ToastProvider></body>
    </html>
  );
}
